/* eslint-disable no-prototype-builtins */
/* eslint-disable @typescript-eslint/no-explicit-any */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.0.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------





export class Commands implements ICommands {
    reset!: KeyboardEvent["code"];
    speedUp!: KeyboardEvent["code"];
    speedDown!: KeyboardEvent["code"];
    speedSet!: KeyboardEvent["code"];

    [key: string]: any;

    constructor(data?: ICommands) {
        if (data) {
            for (const property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (const property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.reset = _data["reset"];
            this.speedUp = _data["speedUp"];
            this.speedDown = _data["speedDown"];
            this.speedSet = _data["speedSet"];
        }
    }

    static fromJS(data: any): Commands {
        data = typeof data === 'object' ? data : {};
        const result = new Commands();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (const property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["reset"] = this.reset;
        data["speedUp"] = this.speedUp;
        data["speedDown"] = this.speedDown;
        data["speedSet"] = this.speedSet;
        return data;
    }
}

export interface ICommands {
    reset: KeyboardEvent["code"];
    speedUp: KeyboardEvent["code"];
    speedDown: KeyboardEvent["code"];
    speedSet: KeyboardEvent["code"];

    [key: string]: any;
}

export class Switch implements ISwitch {
    preserve_pitch!: boolean;
    shortcuts!: boolean;
    ignore_text_field!: boolean;

    [key: string]: any;

    constructor(data?: ISwitch) {
        if (data) {
            for (const property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (const property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.preserve_pitch = _data["preserve_pitch"];
            this.shortcuts = _data["shortcuts"];
            this.ignore_text_field = _data["ignore_text_field"];
        }
    }

    static fromJS(data: any): Switch {
        data = typeof data === 'object' ? data : {};
        const result = new Switch();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (const property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["preserve_pitch"] = this.preserve_pitch;
        data["shortcuts"] = this.shortcuts;
        data["ignore_text_field"] = this.ignore_text_field;
        return data;
    }
}

export interface ISwitch {
    preserve_pitch: boolean;
    shortcuts: boolean;
    ignore_text_field: boolean;

    [key: string]: any;
}

export class Radio implements IRadio {
    speed!: SpeedPitch;
    pitch!: SpeedPitch;

    [key: string]: any;

    constructor(data?: IRadio) {
        if (data) {
            for (const property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (const property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.speed = _data["speed"] ? SpeedPitch.fromJS(_data["speed"]) : <any>undefined;
            this.pitch = _data["pitch"] ? SpeedPitch.fromJS(_data["pitch"]) : <any>undefined;
        }
    }

    static fromJS(data: any): Radio {
        data = typeof data === 'object' ? data : {};
        const result = new Radio();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (const property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["speed"] = this.speed ? this.speed.toJSON() : <any>undefined;
        data["pitch"] = this.pitch ? this.pitch.toJSON() : <any>undefined;
        return data;
    }
}

export interface IRadio {
    speed: SpeedPitch;
    pitch: SpeedPitch;

    [key: string]: any;
}

export class SpeedPitch implements ISpeedPitch {
    preset!: number;
    custom!: CustomSpeedPitch;

    [key: string]: any;

    constructor(data?: ISpeedPitch) {
        if (data) {
            for (const property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (const property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.preset = _data["preset"];
            this.custom = _data["custom"] ? CustomSpeedPitch.fromJS(_data["custom"]) : <any>undefined;
        }
    }

    static fromJS(data: any): SpeedPitch {
        data = typeof data === 'object' ? data : {};
        const result = new SpeedPitch();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (const property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["preset"] = this.preset;
        data["custom"] = this.custom ? this.custom.toJSON() : <any>undefined;
        return data;
    }
}

export interface ISpeedPitch {
    preset: number;
    custom: CustomSpeedPitch;

    [key: string]: any;
}

export class CustomSpeedPitch implements ICustomSpeedPitch {
    plus_minus!: number;
    multiply_divide!: number;

    [key: string]: any;

    constructor(data?: ICustomSpeedPitch) {
        if (data) {
            for (const property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (const property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.plus_minus = _data["plus_minus"];
            this.multiply_divide = _data["multiply_divide"];
        }
    }

    static fromJS(data: any): CustomSpeedPitch {
        data = typeof data === 'object' ? data : {};
        const result = new CustomSpeedPitch();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (const property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["plus_minus"] = this.plus_minus;
        data["multiply_divide"] = this.multiply_divide;
        return data;
    }
}

export interface ICustomSpeedPitch {
    plus_minus: number;
    multiply_divide: number;

    [key: string]: any;
}

export class CommandsData implements ICommandsData {
    version!: number;
    commands!: Commands;
    switch!: Switch;
    radio!: Radio;

    [key: string]: any;

    constructor(data?: ICommandsData) {
        if (data) {
            for (const property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (const property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.version = _data["version"];
            this.commands = _data["commands"] ? Commands.fromJS(_data["commands"]) : <any>undefined;
            this.switch = _data["switch"] ? Switch.fromJS(_data["switch"]) : <any>undefined;
            this.radio = _data["radio"] ? Radio.fromJS(_data["radio"]) : <any>undefined;
        }
    }

    static fromJS(data: any): CommandsData {
        data = typeof data === 'object' ? data : {};
        const result = new CommandsData();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (const property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["version"] = this.version;
        data["commands"] = this.commands ? this.commands.toJSON() : <any>undefined;
        data["switch"] = this.switch ? this.switch.toJSON() : <any>undefined;
        data["radio"] = this.radio ? this.radio.toJSON() : <any>undefined;
        return data;
    }
}

export interface ICommandsData {
    version: number;
    commands: Commands;
    switch: Switch;
    radio: Radio;

    [key: string]: any;
}
